name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

    - name: Download Ngrok
      run: |
        curl -L -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip
        tar -xf ngrok.zip

    - name: Start Ngrok
      run: |
        dir
        .\ngrok.exe authtoken YOUR_NGROK_TOKEN
        .\ngrok.exe tcp 3389
